/* Palette generated by Material Palette - materialpalette.com/teal/amber */
import {StyleSheet, Dimensions} from 'react-native';

export default StyleSheet.create({
  darkprimary: {
    backgroundColor: '#00796B'
  },
  primary: {
    backgroundColor: '#009688'
  },
  lightprimary: {
    backgroundColor: '#B2DFDB'
  },
  textprimary: {
    color: '#F6F7FB'
  },
  accent: {
    backgroundColor: '#FFC107'
  },
  primarytext: {
    color: '#212121'
  },
  secondarytext: {
    color: '#757575'
  },
  divider: {
    borderColor: '#BDBDBD'
  },

});
